name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Check formatting
        run: go fmt ./...

      - name: Check syntax
        run: go vet ./...

  merge-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check if all checks passed
        run: exit $(git log -1 --pretty=format:%s | grep -c "Merge pull request")
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

