name: Go

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Check formatting
        run: go fmt ./...

      - name: Check syntax
        run: go vet ./...

  merge-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check if all checks passed
        run: |
          if [[ $(git log -1 --pretty=format:%s | grep -c "Merge pull request") -eq 0 ]]; then
            echo "All checks passed"
          else
            echo "Checks failed"
            exit 1
          fi
