name: Go

on:
  push:
    branches:
      - '*'
      # Exclude direct pushes to master
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Check formatting
        run: go fmt ./...

      - name: Check syntax
        run: go vet ./...

  merge-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check if all checks passed
        run: exit $(git log -1 --pretty=format:%s | grep -c "Merge pull request")
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

  merge:
    runs-on: ubuntu-latest
    needs: merge-check
    if: github.ref == 'refs/heads/master' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Merge PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
